#!/usr/bin/env python3
"""Regenerate graph/seed.cypher from fixtures/*.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "fixtures"
OUT = ROOT / "graph" / "seed.cypher"


def load(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text())


def esc(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def edge_set(source: str, confidence: float = 1.0) -> str:
    return (
        f"SET e.source = '{source}', e.as_of = date('2026-07-20'), "
        f"e.confidence = {confidence}, e.extractor_version = 'fixtures-v0';"
    )


def main() -> None:
    teams = load("teams.json")
    github = load("github.json")
    aws = load("aws_jobs.json")
    snow = load("snowflake.json")
    pbi = load("powerbi.json")
    jira = load("jira.json")
    conf = load("confluence.json")

    lines: list[str] = [
        "// Auto-generated by scripts/load_seed.py — re-run after fixture edits.",
        "// as_of: 2026-07-20 extractor_version: fixtures-v0",
        "",
        "// --- Nodes ---",
    ]

    for team in teams["teams"]:
        lines.append(
            f"MERGE (t:Team {{id: '{esc(team['id'])}'}}) "
            f"SET t.name = '{esc(team['name'])}', t.cost_center = '{esc(team['cost_center'])}';"
        )
        for member in team["members"]:
            lines.append(
                f"MERGE (p:Person {{id: '{esc(member['id'])}'}}) "
                f"SET p.name = '{esc(member['name'])}', p.slack = '{esc(member['slack'])}';"
            )

    for repo in github["repositories"]:
        lines.append(
            f"MERGE (r:Repository {{id: '{esc(repo['id'])}'}}) "
            f"SET r.url = '{esc(repo['url'])}', r.default_branch = '{esc(repo['default_branch'])}';"
        )

    for job in aws["pipelines"]:
        lines.append(
            f"MERGE (j:Pipeline {{id: '{esc(job['id'])}'}}) "
            f"SET j.name = '{esc(job['name'])}', j.tool = '{esc(job['tool'])}', "
            f"j.env = '{esc(job['env'])}', j.schedule = '{esc(job['schedule'])}', "
            f"j.arn = '{esc(job['arn'])}';"
        )

    for dataset in snow["datasets"]:
        lines.append(
            f"MERGE (d:Dataset {{id: '{esc(dataset['id'])}'}}) "
            f"SET d.fq_name = '{esc(dataset['id'])}', d.object_type = '{esc(dataset['object_type'])}', "
            f"d.layer = '{esc(dataset['layer'])}', d.pii = {str(dataset['pii']).lower()};"
        )

    for model in pbi["semantic_models"]:
        lines.append(
            f"MERGE (m:SemanticModel {{id: '{esc(model['id'])}'}}) "
            f"SET m.name = '{esc(model['name'])}', m.workspace_name = '{esc(model['workspace_name'])}';"
        )

    for report in pbi["reports"]:
        lines.append(
            f"MERGE (rpt:Report {{id: '{esc(report['id'])}'}}) "
            f"SET rpt.name = '{esc(report['name'])}', "
            f"rpt.workspace_name = '{esc(report['workspace_name'])}', "
            f"rpt.criticality = '{esc(report['criticality'])}';"
        )

    for ticket in jira["tickets"]:
        lines.append(
            f"MERGE (tk:Ticket {{id: '{esc(ticket['id'])}'}}) "
            f"SET tk.type = '{esc(ticket['type'])}', tk.status = '{esc(ticket['status'])}', "
            f"tk.priority = '{esc(ticket['priority'])}', tk.url = '{esc(ticket['url'])}';"
        )

    for doc in conf["docs"]:
        lines.append(
            f"MERGE (doc:Doc {{id: '{esc(doc['id'])}'}}) "
            f"SET doc.title = '{esc(doc['title'])}', doc.url = '{esc(doc['url'])}';"
        )

    for term in conf["glossary"]:
        lines.append(
            f"MERGE (g:GlossaryTerm {{id: '{esc(term['id'])}'}}) "
            f"SET g.definition = '{esc(term['definition'])}', g.status = '{esc(term['status'])}';"
        )

    lines.append("")
    lines.append("// --- Edges ---")

    for team in teams["teams"]:
        for member in team["members"]:
            lines.append(
                f"MATCH (p:Person {{id: '{esc(member['id'])}'}}), (t:Team {{id: '{esc(team['id'])}'}}) "
                f"MERGE (p)-[e:MEMBER_OF]->(t) {edge_set('teams')}"
            )
        owns = team["owns"]
        for label, ids, var in [
            ("Dataset", owns["datasets"], "d"),
            ("Pipeline", owns["pipelines"], "j"),
            ("Report", owns["reports"], "rpt"),
            ("Repository", owns["repositories"], "r"),
        ]:
            for node_id in ids:
                lines.append(
                    f"MATCH (t:Team {{id: '{esc(team['id'])}'}}), ({var}:{label} {{id: '{esc(node_id)}'}}) "
                    f"MERGE (t)-[e:OWNS]->({var}) {edge_set('teams')}"
                )

    for repo in github["repositories"]:
        for pipeline_id in repo["implements_pipelines"]:
            lines.append(
                f"MATCH (r:Repository {{id: '{esc(repo['id'])}'}}), "
                f"(j:Pipeline {{id: '{esc(pipeline_id)}'}}) "
                f"MERGE (r)-[e:IMPLEMENTS]->(j) {edge_set('github')}"
            )

    for job in aws["pipelines"]:
        if job.get("repository"):
            lines.append(
                f"MATCH (j:Pipeline {{id: '{esc(job['id'])}'}}), "
                f"(r:Repository {{id: '{esc(job['repository'])}'}}) "
                f"MERGE (j)-[e:DEPLOYS_FROM]->(r) {edge_set('aws_jobs')}"
            )
        for dataset_id in job["reads"]:
            lines.append(
                f"MATCH (j:Pipeline {{id: '{esc(job['id'])}'}}), "
                f"(d:Dataset {{id: '{esc(dataset_id)}'}}) "
                f"MERGE (j)-[e:READS]->(d) {edge_set('aws_jobs')}"
            )
        for dataset_id in job["writes"]:
            lines.append(
                f"MATCH (j:Pipeline {{id: '{esc(job['id'])}'}}), "
                f"(d:Dataset {{id: '{esc(dataset_id)}'}}) "
                f"MERGE (j)-[e:WRITES]->(d) {edge_set('aws_jobs')}"
            )

    for dataset in snow["datasets"]:
        for upstream in dataset["upstream"]:
            lines.append(
                f"MATCH (d:Dataset {{id: '{esc(dataset['id'])}'}}), "
                f"(u:Dataset {{id: '{esc(upstream)}'}}) "
                f"MERGE (d)-[e:DERIVES_FROM]->(u) {edge_set('snowflake')}"
            )

    for model in pbi["semantic_models"]:
        for dataset_id in model["snowflake_datasets"]:
            lines.append(
                f"MATCH (m:SemanticModel {{id: '{esc(model['id'])}'}}), "
                f"(d:Dataset {{id: '{esc(dataset_id)}'}}) "
                f"MERGE (m)-[e:USES]->(d) {edge_set('powerbi')}"
            )

    for report in pbi["reports"]:
        lines.append(
            f"MATCH (rpt:Report {{id: '{esc(report['id'])}'}}), "
            f"(m:SemanticModel {{id: '{esc(report['semantic_model'])}'}}) "
            f"MERGE (rpt)-[e:BINDS]->(m) {edge_set('powerbi')}"
        )
        for dataset_id in report["snowflake_datasets"]:
            lines.append(
                f"MATCH (rpt:Report {{id: '{esc(report['id'])}'}}), "
                f"(d:Dataset {{id: '{esc(dataset_id)}'}}) "
                f"MERGE (rpt)-[e:USES]->(d) {edge_set('powerbi')}"
            )

    for ticket in jira["tickets"]:
        for target in ticket["tracks"]:
            label = target["type"]
            var = {"Dataset": "d", "Pipeline": "j", "Report": "rpt", "Doc": "doc"}[label]
            lines.append(
                f"MATCH (tk:Ticket {{id: '{esc(ticket['id'])}'}}), "
                f"({var}:{label} {{id: '{esc(target['id'])}'}}) "
                f"MERGE (tk)-[e:TRACKS]->({var}) {edge_set('jira')}"
            )

    for doc in conf["docs"]:
        for target in doc["describes"]:
            label = target["type"]
            var = {"Dataset": "d", "GlossaryTerm": "g", "Report": "rpt"}[label]
            lines.append(
                f"MATCH (doc:Doc {{id: '{esc(doc['id'])}'}}), "
                f"({var}:{label} {{id: '{esc(target['id'])}'}}) "
                f"MERGE (doc)-[e:DESCRIBES]->({var}) {edge_set('confluence')}"
            )

    for term in conf["glossary"]:
        for dataset_id in term["defined_by_datasets"]:
            confidence = 0.6 if term["id"] == "campaign_roi" and "orders" in dataset_id else 1.0
            lines.append(
                f"MATCH (d:Dataset {{id: '{esc(dataset_id)}'}}), "
                f"(g:GlossaryTerm {{id: '{esc(term['id'])}'}}) "
                f"MERGE (d)-[e:DEFINES]->(g) {edge_set('confluence', confidence)}"
            )

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
